name: release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install node.js dependencies
        run: npm ci

      - name: Build and zip UI-Plugin
        run : |
          UI_VERSION=$(jq -r .version package.json)
          npm run build
          mv dist/tedge-container-plugin-ui.zip "dist/tedge-container-plugin-ui_${UI_VERSION}.zip"

      - name: Upload
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ github.ref_name }}" --generate-notes --draft ||:
          gh release upload "${{ github.ref_name }}" dist/tedge-container-plugin-ui_*.zip
